# Copyright (c) 2016-2021 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Hitachi Cloud Accelerator Platform Documentation
# site_url: https://squidfunk.github.io/mkdocs-material/
# site_author: Martin Donath
# site_description: >-
#   Create a branded static site from a set of Markdown files to host the
#   documentation of your Open Source or commercial project – customizable,
#   searchable, mobile-friendly, 40+ languages

# Repository
repo_name: HCAP_doc
repo_url: https://arnab20ghosh.github.io/HCAP_doc/
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016 - 2021 Martin Donath

# Configuration
theme:
  name: null
  custom_dir: material

  # Static files
  # static_templates:
  #   - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: black
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: 

# Plugins
plugins:
  - search
  # - redirects:
  #     redirect_maps:
  #       extensions/admonition.md: reference/admonitions.md
  #       extensions/codehilite.md: reference/code-blocks.md
  #       extensions/footnotes.md: reference/footnotes.md
  #       extensions/metadata.md: reference/meta-tags.md
  #       extensions/permalinks.md: setup/setting-up-navigation.md #permalink
  #       extensions/pymdown.md: reference/admonitions.md
  #       plugins/revision-date.md: setup/adding-a-git-repository.md #revision-date
  #       plugins/search.md: setup/setting-up-site-search.md
  #       releases/4.md: upgrading.md #upgrading-from-4x-to-5x
  #       releases/5.md: upgrading.md #upgrading-from-3x-to-4x
  #       releases/changelog.md: changelog.md
  #       setup/adding-social-links.md: setup/setting-up-the-footer.md
  #       sponsorship.md: insiders.md
  - minify:
      minify_html: true

# Customization
# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/squidfunk
#     - icon: fontawesome/brands/gitter
#       link: https://gitter.im/squidfunk/mkdocs-material
#     - icon: fontawesome/brands/docker
#       link: https://hub.docker.com/r/squidfunk/mkdocs-material/
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/squidfunk
#     - icon: fontawesome/brands/linkedin
#       link: https://linkedin.com/in/squidfunk/
#     - icon: fontawesome/brands/instagram
#       link: https://instagram.com/squidfunk

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Get started:
    - Get Started: platform-common/getStarted.md
    - Deploy and configure: platform-common/deployAndConfigure.md
    - Administer: platform-common/administer.md
    - Create & access account: platform-common/createAndAccessAccount.md
    - Install and use Platform CLI: platform-common/cliTool.md
  - Accelerators:
    - Deploy Accelerator: 
      - Overview: deploy/getting-started.md
      - Deploy and Manage:
        - Deploy: deploy/using_copy.md
      - Administer: deploy/administering.md
      - How-to guides: deploy/howto-guides.md
      - API reference: deploy/api-reference.md
    - Workflow Accelerator:
      - Overview: workflow/getting-started.md
      - Understand the solution package schema: workflow/understand-solution-package-schema.md
      - Create and register solution package: workflow/using.md
      - Deploy solution package: workflow/deploy-package.md
      - API reference: workflow/api-reference.md
    - Test Accelerator:
      - Overview: test/getting-started.md
      - Run tests: test/using.md
      - Administer: test/administer.md
      - API reference: test/api-reference.md
    - Assess Accelerator:
      - Overview: assess/getting-started.md
      - Run assessment policies: assess/using.md
      - Create and manage assessment templates: assess/assess-templates.md
      - Assessment checks reference: assess/assess-checks.md
    - Migrate Accelerator:
      - Overview: migrate/getting-started.md
      - Discover and migrate resources: migrate/using.md
      - Administer: migrate/administering.md
  - DevSecOps:
    - devops/gettingStarted.md
    - Image Pipeline: 
      - Overview: devsecops/Overview.md
      - Configure a DevSecOps workstation: devsecops/Configuring-a-DevSecOps-Workstation.md
      - Create project: devsecops/Creating-Projects.md
      - Configure project: devsecops/Creating-Projects.md
      - Build and test from Jenkins: devsecops/Building-and-Testing-from-Jenkins.md
      - Build and test from your workstation: devsecops/Building-and-Testing-from-your-Workstation.md
      - External configurations: devsecops/External-Configuration.md
      - Customize projects: devsecops/Customizing-projects.md
      - Learn the concepts: devsecops/Learn-the-concepts.md
      - Set-up a Linux Virtual Machine: devsecops/Windows-Linux-Virtual-Machine-Setup.md
  - Infobytes:
    - Deploy: deploy-infobytes/info-btyes.md
    - Infobyte 1- Product overview: deploy-infobytes/info-btyes-01.md
    - Infobyte 2- Layered environments: deploy-infobytes/info-btyes-02.md
    - Infobyte 3- Multiple deployment: deploy-infobytes/info-btyes-03.md
    - Infobyte 4- Environment versions and releases: deploy-infobytes/info-btyes-04.md
    - Infobyte 5- Blueprints: deploy-infobytes/info-btyes-05.md
    - Infobyte 6- Packages: deploy-infobytes/info-btyes-06.md
    - Infobyte 7- Platform CLI tool: deploy-infobytes/info-btyes-07.md
  - What's New?:
    - Latest Releases: platform-common/whatsNew.md
    - Archive: platform-common/whatsNewArchive.md


# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
